export const SET_VIDEOS = "SET_VIDEOS";
export const SET_SUBSCRIPTIONS = "SET_SUBSCRIPTIONS";
export const SET_PLAYLISTS = "SET_PLAYLISTS";
export const SET_VIDEO = "SET_VIDEO";
export const SET_COMMENTS = "SET_COMMENTS";
export const TOGGLE_ISVIDEOFETCHING_STATE = "TOGGLE_ISVIDEOFETCHING_STATE";
export const TOGGLE_ISPLAYLIST_FETCHING_STATE =
  "TOGGLE_ISPLAYLIST_FETCHING_STATE";
export const TOGGLE_ISPLAYLIST_CREATING_STATE =
  "TOGGLE_ISPLAYLIST_CREATING_STATE";
export const TOGGLE_IS_COMMENT_FETCHING_STATE =
  "TOGGLE_IS_COMMENT_FETCHING_STATE";
export const TOGGLE_IS_CURRENT_VIDEOFETCHING_STATE =
  "TOGGLE_IS_CURRENT_VIDEOFETCHING_STATE";
export const TOGGLE_ISUSERFETCHING_STATE = "TOGGLE_ISUSERFETCHING_STATE";
export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const CREATE_PLAYLISTS = "CREATE_PLAYLISTS";
export const SET_CHANNEL_DATA = "SET_CHANNEL_DATA";
export const TOGGLE_CHANNEL_DATA_FETCHING_STATE =
  "TOGGLE_CHANNEL_DATA_FETCHING_STATE";
export const TOGGLE_ISSUBSCRIPTIONS_FETCHING_STATE =
  "TOGGLE_ISSUBSCRIPTIONS_FETCHING_STATE";
